apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::226575302242:role/takeon-dev-sandbox-node-stack-NodeInstanceRole-1T8HM1EKNBQ75
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::226575302242:role/takeon-eks-role
      username: admin:{{SessionName}}
      groups:
        - system:masters